### PR TITLE
Quiz App

### PR DESCRIPTION
**Pull request by samraj-freak**
Final code for quiz app
Screenshot 2023-10-04 142321
Screenshot 2023-10-04 142336

### CODE REVIEW

**Comment by Kritika30032002** [comment]
add gitignore file

node modules are never uploaded

**Comment by samraj-freak** [comment]
changes have been made

**Comment by Kritika30032002** [comment]
update the readme too.

**Comment by samraj-freak** [comment]
Readme Updated

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Pull request merged**
