### PR TITLE
Solved Issue: Portfolio Website #17 - Created a portfolio website using React

### PR DESCRIPTION
**Pull request by eatulrajput**
Solved Issue - Portfolio Website #17 : Create a portfolio website using React

### CODE REVIEW

**Comment by Kritika30032002** [comment]
update readme

**Comment by eatulrajput** [comment]
Updated README.md file.

**Comment by Kritika30032002** [comment]
refer to other added project readme for reference

**Comment by eatulrajput** [comment]
Updated README.md file, please check it.

**Comment by eatulrajput** [comment]
Done

**Comment by eatulrajput** [comment]
Is there is any problem in accepting pull request?

**Review by Kritika30032002 — APPROVED** [review]

**Pull request merged**
