### PR TITLE
Dice Game using react

### PR DESCRIPTION
**Pull request by Sanketmane2323**
Dice Game added

### CODE REVIEW

**Comment by Kritika30032002** [comment]
add proper readme

**Comment by Sanketmane2323** [comment]
Hey @Kritika30032002  I have added the readme file to the project can you go through it.

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Comment by Sanketmane2323** [comment]
Thanks @Kritika30032002

**Pull request merged**
