### PR TITLE
Added quiz app

### LINKED ISSUE #21: Quiz App
I want to add a React quiz app. Please assign me to this under hacktoberfest23.

### PR DESCRIPTION
**Pull request by Manveer-Pbx1**
fixes #21

### CODE REVIEW

**Comment by Kritika30032002** [comment]
add in separate folder with updated readme

**Comment by Manveer-Pbx1** [comment]
Updated!

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Comment by Manveer-Pbx1** [comment]
> Thanks for your valuable contribution. Don't forget to star the repo.

Sure, thank you for merging my first ever pull request!

**Pull request merged**
