### PR TITLE
Apps info Webapp

### LINKED ISSUE #126: [Project] Applications Information Webapp
Photos 21-12-2023 01_08_31 PM

**I am participating in Codepeak**

### PR DESCRIPTION
**Pull request by AaadityaG**
Close #126

participating in Codepeak

### CODE REVIEW

**Comment by Kritika30032002** [comment]
update readme

**Review by AaadityaG — COMMENTED** [review]
@Kritika30032002 readme update is done!

**Comment by Kritika30032002** [comment]
clone code line is wrong

**Comment by AaadityaG** [comment]
Sorry, I didn't understand, would you elaborate?

**Review by AaadityaG — COMMENTED** [review]
Its done!

**Pull request merged**
