### PR TITLE
CryptoApp

### PR DESCRIPTION
**Pull request by Shivam250702**
A React Application for Crypto Enthusiasts

### CODE REVIEW

**Comment by Kritika30032002** [comment]
update readme

**Comment by Kritika30032002** [comment]
program name?

**Comment by Shivam250702** [comment]
I have made necessary changes please check

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Comment by Kritika30032002** [comment]
program name?

**Pull request merged**
