### PR TITLE
Currency converter project added

### PR DESCRIPTION
**Pull request by Sami3160**
Currency Converter
issue  #118
-This project made using typescipt with react 
-and using ExchangeRate API which gives Realtime rates of currencies and dynamically gives correct converted value, As api used it has capacity of 1500 requests, after that someone needs to renew the api, well in readme.md i have mentioned it all how to get new api key.
Again it shows very accurate conversion base on updated global market.
Screen shot;
292637266-b3bb5422-58a2-4efd-90e0-2fdaf8b69e14

### CODE REVIEW

**Comment by Kritika30032002** [comment]
add readme

**Comment by Sami3160** [comment]
> add readme
@Kritika30032002  look at yellow rectangle, their is a readme, the screen shot is of this current pr
Screenshot_20231226_224942

**Comment by Kritika30032002** [comment]
add git clone and cd steps

**Comment by Sami3160** [comment]
> add git clone and cd steps

done mam!

**Comment by Kritika30032002** [comment]
firstly it has conflicts
secondly it has no readme

**Comment by Sami3160** [comment]
> firstly it has conflicts secondly it has no readme

@Kritika30032002   mam i wanted to resolve the conflicts long ago, but the resolve conflicts button was disables...idk why and abaout readme, their is one, i promise im not lying
check this video, here you can that readme is right their

https://github.com/Kritika30032002/ReactCreations/assets/110652247/94597d76-3622-49d7-ab60-ea656f411bc7

**Comment by Kritika30032002** [comment]
image


see these conflicts

**Comment by Sami3160** [comment]
> image
> 
> see these conflicts

Mam seriously i do wanna resolve conflicts, but the button is disabled :(
Screenshot_20231228_235058
see here...   :(

**Comment by Kritika30032002** [comment]
again fork my repo 
add your project 
then send the pr

**Pull request closed without merging**
