### PR TITLE
added crypto-tracker

### LINKED ISSUE #120: Crypto Price tracker
Use tailwind css, next.js and react to create a Crypto Price Tracker

### PR DESCRIPTION
**Pull request by aindree-2005**
closes #120

### CODE REVIEW

**Comment by aindree-2005** [comment]
https://github.com/Kritika30032002/ReactCreations/assets/68018372/f62cf53f-f2b3-42c8-a889-f0db4f54ed8d

**Comment by aindree-2005** [comment]
@Kritika30032002 added working demo too

**Comment by Kritika30032002** [comment]
add in proper folder

**Comment by aindree-2005** [comment]
> add in proper folder

Could you please help with that. I can see it being Accessible in VS Code but not on github

**Comment by GAGANRAGHAV** [comment]
@aindree-2005 you are trying to add your previously existing github pushed project ..thats why it is coming in sum module ...please make a new folder without .git file in it ..remove it by unhiding the hidden icons.

**Pull request closed without merging**
