### PR TITLE
Added ToDo app made on react and django

### LINKED ISSUE #229: Todo list madeon React + Django, dockerised and with backend
React and Django connected using API. Provided with Readme. The application is dockerised too and is on postresql.

### PR DESCRIPTION
**Pull request by praptisharma28**
closes #229

### CODE REVIEW

**Comment by praptisharma28** [comment]
have a look @Kritika30032002

**Comment by Kritika30032002** [comment]
add readme with 
1. proper steps of local setup and running the code
2. video of working
3. tech stack used

**Comment by Kritika30032002** [comment]
also add gitignore

**Comment by praptisharma28** [comment]
.gitignore, readme, how to run all of these things are already there, I am adding the video too @Kritika30032002

**Comment by praptisharma28** [comment]
done @Kritika30032002

**Pull request merged**
