### PR TITLE
added the certificate generation application in a /certificate route 

### PR DESCRIPTION
**Pull request by mohammedasimahmed**
I added a .gitignore file and the certificate generation application that generates a pdf of your certificate ,  the certificate generation app can help organisations to generate pdf's of certificate easily by entering the organisation , candidate , course name in the form on the left

### CODE REVIEW

**Comment by Kritika30032002** [comment]
Have you added your project in separate folder?

**Comment by mohammedasimahmed** [comment]
no i made a separate route called /certificate in the GithubUsers-master , do u want it to be a separate folder?

**Comment by Kritika30032002** [comment]
GitHubUsers master is a separate project folder.

Put you project  in separate folder with proper readme.

**Comment by mohammedasimahmed** [comment]
alright

**Pull request closed without merging**
