### PR TITLE
password generator added

### LINKED ISSUE #228: Password Generator made on Reactjs
Made with 65% JavaScript. This web app builds passwords and is fully functional.

### PR DESCRIPTION
**Pull request by praptisharma28**
closes #228

### CODE REVIEW

**Comment by praptisharma28** [comment]
@Kritika30032002

**Comment by Kritika30032002** [comment]
add proper git commands of local setup
also add video of project

**Comment by Kritika30032002** [comment]
in readme

**Comment by praptisharma28** [comment]
done @Kritika30032002 hv a look plz

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Pull request merged**
