### PR TITLE
To Do Webapp

### LINKED ISSUE #125: [Project]  - To Do Webapp
AaadityaG_To-do-webapp - Google Chrome 20-12-2023 09_11_25 PM

### PR DESCRIPTION
**Pull request by AaadityaG**
Close #125

Participating in Codepeak

### CODE REVIEW

**Comment by Kritika30032002** [comment]
update readme with local setup steps

**Review by AaadityaG — COMMENTED** [review]
Upating Readme.md done!

**Comment by Kritika30032002** [comment]
clone code line not correct in readme

**Review by AaadityaG — COMMENTED** [review]
Its done!

**Review by Kritika30032002 — APPROVED** [review]

**Pull request merged**
