### PR TITLE
React With Router Template (pd)

### PR DESCRIPTION
**Pull request by oriapp**
I made a while ago a react app template, that I use until today for base making other sites. It already includes router and validation etc… so It makes the job easier when making new projects.

### CODE REVIEW

**Comment by Kritika30032002** [comment]
@oriapp there is some issue with the folder. Look into it !

**Comment by oriapp** [comment]
What's the issue?

**Comment by oriapp** [comment]
I created a new pull with the files, sorry.

**Comment by Kritika30032002** [comment]
Okay

**Pull request merged**
