### PR TITLE
Code with dhruv

### PR DESCRIPTION
**Pull request by Dhruv127**

### CODE REVIEW

**Comment by Dhruv127** [comment]
@Kritika30032002  my both the prs get merge together , so please assign the points accordingly . I have created this pr for the same . Thank you

**Comment by Kritika30032002** [comment]
which pr got merged together ?

**Comment by Dhruv127** [comment]
codewithdhruv and saloon booking website were merged together

**Comment by Dhruv127** [comment]
?

**Comment by Dhruv127** [comment]
@Kritika30032002

**Pull request closed without merging**
