### PR TITLE
Added currency converter Webapp

### PR DESCRIPTION
**Pull request by SoumyadevSaha**
Closes Issue #118 

### Description
Created new folder `Currency Converter` containing the currency converter app under @ IWOC 2.0 @ 2024. Readme.md file has been added and contains necessary instructions to run the app.

### Video Demo

https://github.com/Kritika30032002/ReactCreations/assets/86418216/1a986f59-d4c0-4508-a33e-48974c9113f9

### CODE REVIEW

**Comment by Kritika30032002** [comment]
in readme , instructions for local setup are not mentioned

**Comment by SoumyadevSaha** [comment]
> in readme , instructions for local setup are not mentioned

I see ... working on it.

**Comment by SoumyadevSaha** [comment]
Hi @Kritika30032002 updated the instructions in readme.md for local setup. please check.

**Review by Kritika30032002 — APPROVED** [review]

**Comment by SoumyadevSaha** [comment]
Hi @Kritika30032002 could you kindly assign this PR to me ? It seems that this contribution is not getting reflected on my dashboard as it has no assignees

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Comment by SoumyadevSaha** [comment]
> Thanks for your Valuable contribution. Don't forget to star the repo.

Thanks for the great opportunity as well 😁

**Pull request merged**
