### PR TITLE
feat: Added Youtube Clone

### LINKED ISSUE #226: Youtube Clone
Adding a Youtube Clone with both frontend and backend

Please assign this to me under IWOC

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
# Fixes Issue🛠️

Closes #226 

# Description👨‍💻 
I have added a Youtube Clone with both frontend and backend with a Readme and a video of working

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added a demonstration in the form of a GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Kritika30032002/ReactCreations/assets/140608790/4afea85b-76df-4af9-a017-ecd77b70e644

### CODE REVIEW

**Comment by Kritika30032002** [comment]
update readme

**Comment by JiyaGupta-cs** [comment]
@Kritika30032002 what to update in readme ma'am?

**Comment by JiyaGupta-cs** [comment]
@Kritika30032002 ?

**Comment by Kritika30032002** [comment]
add readme with
1. proper steps of local setup and running the code
2. video of working
3. tech stack used

**Comment by JiyaGupta-cs** [comment]
@Kritika30032002 
I have added add readme with proper steps of local setup and running the code, video of working and the tech stack used

**Comment by JiyaGupta-cs** [comment]
> @Kritika30032002 I have added add readme with proper steps of local setup and running the code, video of working and the tech stack used

Please review

**Comment by JiyaGupta-cs** [comment]
> @Kritika30032002 I have added add readme with proper steps of local setup and running the code, video of working and the tech stack used

Please see to it

**Comment by JiyaGupta-cs** [comment]
> @Kritika30032002 I have added add readme with proper steps of local setup and running the code, video of working and the tech stack used

@Kritika30032002 Please review it, it's been a long time

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Pull request merged**
