### PR TITLE
added a new folder certificate-generator 

### PR DESCRIPTION
**Pull request by mohammedasimahmed**
certificate-genearator folder contains an application that allows organisations to generate a certificate pdf by entering the candidate,organisation,course name in the form on the left side

### CODE REVIEW

**Comment by mohammedasimahmed** [comment]
could you please review this and tell me whether this is to your liking

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution. Don't forget to star the repo.

**Comment by mohammedasimahmed** [comment]
your welcome and thanks for accepting my pull request but could you please add the hacktoberfest label on my pull request

**Comment by Kritika30032002** [comment]
done

Don't forget to star the repo.

**Pull request merged**
