### PR TITLE
add instagram clone

### PR DESCRIPTION
**Pull request by hemant933**
#221

### CODE REVIEW

**Comment by Kritika30032002** [comment]
add video of working in readme
also by reading the readme, the user must be able to locally run the program so setup the readme accordingly

**Comment by hemant933** [comment]
> add video of working in readme also by reading the readme, the user must be able to locally run the program so setup the readme accordingly

I updated the Readme.md file

**Comment by Kritika30032002** [comment]
Create a `config/config.js` file and insert the following code it will contains all code variables. Replace values with yours !!!

    PORT=YOUR_PORT
    SESSION_SECRET_LETTER="anything-secret"
    MYSQL_HOST="host"
    MYSQL_USER="user"
    MYSQL_PASSWORD="password"
    MYSQL_DATABASE="db"
    MAIL="your-email-for-sending email-verification-link"
    MAIL_PASSWORD="password-for-email"
    GOOGLE_GEOLOCATION_KEY='google-geolocation-key'
    ADMIN_PASSWORD='password-for-admin'
    
    
    add from where and how user can get its value (add any utube video or website which guide getting these values)

**Comment by hemant933** [comment]
> Create a `config/config.js` file and insert the following code it will contains all code variables. Replace values with yours !!!
> 
> ```
> PORT=YOUR_PORT
> SESSION_SECRET_LETTER="anything-secret"
> MYSQL_HOST="host"
> MYSQL_USER="user"
> MYSQL_PASSWORD="password"
> MYSQL_DATABASE="db"
> MAIL="your-email-for-sending email-verification-link"
> MAIL_PASSWORD="password-for-email"
> GOOGLE_GEOLOCATION_KEY='google-geolocation-key'
> ADMIN_PASSWORD='password-for-admin'
> 
> 
> add from where and how user can get its value (add any utube video or website which guide getting these values)
> ```

done

**Review by Kritika30032002 — APPROVED** [review]

**Pull request merged**
