### PR TITLE
Wordle Clone app

### PR DESCRIPTION
**Pull request by Vector-013**
feat #195 : Created Wordle clone using react running on a yarn server

### CODE REVIEW

**Comment by Kritika30032002** [comment]
node modules should not be added

**Comment by Kritika30032002** [comment]
update readme

**Comment by Vector-013** [comment]
Shall I rectify these and make a new PR?

**Comment by Kritika30032002** [comment]
yes

**Comment by Kritika30032002** [comment]
add .gitignore file

**Comment by Kritika30032002** [comment]
with video of project

**Comment by Vector-013** [comment]
Ok, I have added a gitignore as well. Should I make a seperate "demo" folder containing images of the gameplay as there is guessing time in the video as well ?

**Comment by Kritika30032002** [comment]
show video of project to me here in chat

**Pull request closed without merging**
