### PR TITLE
Added Accordion

### LINKED ISSUE #202: Accordion
To Create a Accordion for the collections of this Repository 
/assign me with IWOC

### PR DESCRIPTION
**Pull request by AbhineshJha**
## Fixes #202 
Added the accordion in the collection of the react repo>>

image

### CODE REVIEW

**Comment by Kritika30032002** [comment]
update readme

**Comment by AbhineshJha** [comment]
done @Kritika30032002

**Comment by Kritika30032002** [comment]
refer to other project readme to know how the readme should be

**Comment by AbhineshJha** [comment]
now have a review @Kritika30032002

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Pull request merged**
