### PR TITLE
NTF GAME

### PR DESCRIPTION
**Pull request by Bayyana-kiran**
ADDES #134
ONCE KINDLY CHECK AND ACCEPT THE PR @Kritika30032002

### CODE REVIEW

**Comment by Kritika30032002** [comment]
show video also add it in readme

**Comment by Kritika30032002** [comment]
also update readme

**Comment by Bayyana-kiran** [comment]
@Kritika30032002 once check updates readme file

**Comment by Bayyana-kiran** [comment]
Make sure user is able to connect the game through metamask extension and connect it manually
THANK YOU

**Comment by Kritika30032002** [comment]
show video also add it in readme

**Comment by Kritika30032002** [comment]
update everything about its setup in readme

**Comment by Bayyana-kiran** [comment]
@Kritika30032002 everything is updated already its normal as a game ....anyone can access through the metamask. What changes has to be done can u specify?

**Comment by Bayyana-kiran** [comment]
@Kritika30032002???

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Pull request merged**
