### PR TITLE
Discord Clone

### PR DESCRIPTION
**Pull request by Mayank77maruti**
SCREENSHOTS   Issue: #168 
frienddis
regisdis
disfeat
frienddis123

### CODE REVIEW

**Comment by Kritika30032002** [comment]
update readme properly

**Comment by Mayank77maruti** [comment]
Hey @Kritika30032002 , I have updated the readme if i have to update it further please do tell.

**Comment by Kritika30032002** [comment]
@Mayank77maruti  add git clone and cd code line
refer to other readme for example

**Comment by Mayank77maruti** [comment]
Hey @Kritika30032002  In commit [18ac119](https://github.com/Kritika30032002/ReactCreations/pull/175/commits/18ac1199c40cd6121f9fd75db869c60a74b1ecba) I have fixed the read me accordingly.

**Comment by Kritika30032002** [comment]
send fresh pr

**Comment by Mayank77maruti** [comment]
Hwy @Kritika30032002 , I have opend a new pr please do review.

**Pull request closed without merging**
