### PR TITLE
Added Quote Generation React App

### PR DESCRIPTION
**Pull request by Ved091**
In this pull request I have added Quote Generation React App
It fixes : #22
Screenshot (202)

### CODE REVIEW

**Comment by Kritika30032002** [comment]
remove the heading project 3
as this is individual project not project no. 3

**Comment by Ved091** [comment]
Removed the heading "Project 3"

**Comment by Kritika30032002** [comment]
add it in a proper separate folder.

**Comment by Ved091** [comment]
I am making a new pull request so I am closing this one

**Pull request closed without merging**
