### PR TITLE
feat: Added Minecraft

### LINKED ISSUE #234: Minecraft Clone
# Description:- 

It has 5 types of blocks: Grass, Wood, Log, Glass, and Dirt. You switch blocks with numbers 1-5 on your keyboard. You navigate the world with the mouse and WASD. You can click to add blocks and Alt+Click to remove blocks. Your world is stored in your browser's local storage.

image

Please assign me this under IWOC

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
# Fixes Issue🛠️

Closes #234 

# Description👨‍💻 

I have added Minecraft Clone

It has 5 types of blocks: Grass, Wood, Log, Glass, and Dirt. You switch blocks with numbers 1-5 on your keyboard. You navigate the world with the mouse and WASD. You can click to add blocks and Alt+Click to remove blocks. Your world is stored in your browser's local storage.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added a demonstration in the form of a GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Kritika30032002/ReactCreations/assets/140608790/45b406ff-5247-425e-90a7-05ff6d541f8b

### CODE REVIEW

**Comment by Kritika30032002** [comment]
add readme

**Comment by Kritika30032002** [comment]
add readme with
1. proper steps of local setup(git commands) and running the code(how to run locally)
2. video of working
3. tech stack used

**Comment by JiyaGupta-cs** [comment]
@Kritika30032002 
I have added the setup guidelines and the demo video to it
Please review the PR
And could you please change the label to "hard"?

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Pull request merged**
