### PR TITLE
React router with validation

### PR DESCRIPTION
**Pull request by oriapp**
(mainly use for a skeleton for new projects)

### CODE REVIEW

**Comment by Kritika30032002** [comment]
create a proper readme with the guidelines to run it on local server

**Comment by oriapp** [comment]
There is already one. check pull

**Comment by Kritika30032002** [comment]
readme is there but not local setup steps

**Comment by oriapp** [comment]
I added how to clone.

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution. Don't forget to star the repository.

**Pull request merged**
