### PR TITLE
Added Budget App

### PR DESCRIPTION
**Pull request by EjDadivas**
image

#61

### CODE REVIEW

**Comment by EjDadivas** [comment]
@Kritika30032002 please review. Thank you

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Comment by EjDadivas** [comment]
Already starred.@Kritika30032002, Can you label this for hacktoberfest?

**Comment by Kritika30032002** [comment]
done

**Pull request merged**
